# 定义 stages
stages:
  - built_in_deploy
  - publish
  

# 定义job
built_in_deploy:
  stage: built_in_deploy
  cache: {}
  tags:
    - block-design-live
  script:
    - bash ./built-in-deploy.sh

publish:
  stage: publish
  tags:
    - block-design-live
  script:
    - cd docker && cp /home/gitlab-runner/.tmp/id_rsa* ./ && docker build -t registry.cn-shenzhen.aliyuncs.com/block-design/block-design-live:uniapp-uview-vue3 . --no-cache
    - docker push registry.cn-shenzhen.aliyuncs.com/block-design/block-design-live:uniapp-uview-vue3
