#!/bin/bash
 node scripts/parse_props.mjs u-action-sheet
 node scripts/parse_props.mjs u-album
 node scripts/parse_props.mjs u-alert
 node scripts/parse_props.mjs u-avatar
 node scripts/parse_props.mjs u-avatar-group
 node scripts/parse_props.mjs u-back-top
 node scripts/parse_props.mjs u-badge
 node scripts/parse_props.mjs u-button
 node scripts/parse_props.mjs u-calendar
 node scripts/parse_props.mjs u-car-keyboard
 node scripts/parse_props.mjs u-cell
 node scripts/parse_props.mjs u-cell-group
 node scripts/parse_props.mjs u-checkbox
 node scripts/parse_props.mjs u-checkbox-group
 node scripts/parse_props.mjs u-circle-progress
 node scripts/parse_props.mjs u-code
 node scripts/parse_props.mjs u-code-input
 node scripts/parse_props.mjs u-col
 node scripts/parse_props.mjs u-collapse
 node scripts/parse_props.mjs u-collapse-item
 node scripts/parse_props.mjs u-column-notice
 node scripts/parse_props.mjs u-count-down
 node scripts/parse_props.mjs u-count-to
 node scripts/parse_props.mjs u-datetime-picker
 node scripts/parse_props.mjs u-divider
 node scripts/parse_props.mjs u-dropdown
 node scripts/parse_props.mjs u-dropdown-item
 node scripts/parse_props.mjs u-empty
 node scripts/parse_props.mjs u-form
 node scripts/parse_props.mjs u-form-item
 node scripts/parse_props.mjs u-gap
 node scripts/parse_props.mjs u-grid
 node scripts/parse_props.mjs u-grid-item
 node scripts/parse_props.mjs u-icon
 node scripts/parse_props.mjs u-image
 node scripts/parse_props.mjs u-index-anchor
 node scripts/parse_props.mjs u-index-item
 node scripts/parse_props.mjs u-index-list
 node scripts/parse_props.mjs u-input
 node scripts/parse_props.mjs u-keyboard
 node scripts/parse_props.mjs u-line
 node scripts/parse_props.mjs u-line-progress
 node scripts/parse_props.mjs u-link
 node scripts/parse_props.mjs u-list
 node scripts/parse_props.mjs u-list-item
 node scripts/parse_props.mjs u-loading-icon
 node scripts/parse_props.mjs u-loading-page
 node scripts/parse_props.mjs u-loadmore
 node scripts/parse_props.mjs u-modal
 node scripts/parse_props.mjs u-navbar
 node scripts/parse_props.mjs u-no-network
 node scripts/parse_props.mjs u-notice-bar
 node scripts/parse_props.mjs u-notify
 node scripts/parse_props.mjs u-number-box
 node scripts/parse_props.mjs u-number-keyboard
 node scripts/parse_props.mjs u-overlay
 node scripts/parse_props.mjs u-parse
 node scripts/parse_props.mjs u-picker
 node scripts/parse_props.mjs u-picker-column
 node scripts/parse_props.mjs u-popup
 node scripts/parse_props.mjs u-radio
 node scripts/parse_props.mjs u-radio-group
 node scripts/parse_props.mjs u-rate
 node scripts/parse_props.mjs u-read-more
 node scripts/parse_props.mjs u-row
 node scripts/parse_props.mjs u-row-notice
 node scripts/parse_props.mjs u-safe-bottom
 node scripts/parse_props.mjs u-scroll-list
 node scripts/parse_props.mjs u-search
 node scripts/parse_props.mjs u-skeleton
 node scripts/parse_props.mjs u-slider
 node scripts/parse_props.mjs u-status-bar
 node scripts/parse_props.mjs u-steps
 node scripts/parse_props.mjs u-steps-item
 node scripts/parse_props.mjs u-sticky
 node scripts/parse_props.mjs u-subsection
 node scripts/parse_props.mjs u-swipe-action
 node scripts/parse_props.mjs u-swipe-action-item
 node scripts/parse_props.mjs u-swiper
 node scripts/parse_props.mjs u-swiper-indicator
 node scripts/parse_props.mjs u-switch
 node scripts/parse_props.mjs u-tabbar
 node scripts/parse_props.mjs u-tabbar-item
 node scripts/parse_props.mjs u-table
 node scripts/parse_props.mjs u-tabs
 node scripts/parse_props.mjs u-tabs-item
 node scripts/parse_props.mjs u-tag
 node scripts/parse_props.mjs u-td
 node scripts/parse_props.mjs u-text
 node scripts/parse_props.mjs u-textarea
 node scripts/parse_props.mjs u-toast
 node scripts/parse_props.mjs u-toolbar
 node scripts/parse_props.mjs u-tooltip
 node scripts/parse_props.mjs u-tr
 node scripts/parse_props.mjs u-transition
 node scripts/parse_props.mjs u-upload
echo "解析完成！"