#!/bin/bash
npm run parse u-action-sheet
npm run parse u-alert-tips
npm run parse u-avatar
npm run parse u-avatar-cropper
npm run parse u-back-top
npm run parse u-badge
npm run parse u-button
npm run parse u-calendar
npm run parse u-car-keyboard
npm run parse u-card
npm run parse u-cell-group
npm run parse u-cell-item
npm run parse u-checkbox
npm run parse u-checkbox-group
npm run parse u-circle-progress
npm run parse u-col
npm run parse u-collapse
npm run parse u-collapse-item
npm run parse u-column-notice
npm run parse u-count-down
npm run parse u-count-to
npm run parse u-divider
npm run parse u-dropdown
npm run parse u-dropdown-item
npm run parse u-empty
npm run parse u-field
npm run parse u-form
npm run parse u-form-item
npm run parse u-full-screen
npm run parse u-gap
npm run parse u-grid
npm run parse u-grid-item
npm run parse u-icon
npm run parse u-image
npm run parse u-index-anchor
npm run parse u-index-list
npm run parse u-input
npm run parse u-keyboard
npm run parse u-lazy-load
npm run parse u-line
npm run parse u-line-progress
npm run parse u-link
npm run parse u-loading
npm run parse u-loading-page
npm run parse u-loadmore
npm run parse u-mask
npm run parse u-message-input
npm run parse u-modal
npm run parse u-navbar
npm run parse u-no-network
npm run parse u-notice-bar
npm run parse u-number-box
npm run parse u-number-keyboard
npm run parse u-parse
npm run parse u-picker
npm run parse u-popup
npm run parse u-radio
npm run parse u-radio-group
npm run parse u-rate
npm run parse u-read-more
npm run parse u-row
npm run parse u-row-notice
npm run parse u-search
npm run parse u-section
npm run parse u-select
npm run parse u-skeleton
npm run parse u-slider
npm run parse u-steps
npm run parse u-sticky
npm run parse u-subsection
npm run parse u-swipe-action
npm run parse u-swiper
npm run parse u-switch
npm run parse u-tabbar
npm run parse u-table
npm run parse u-tabs
npm run parse u-tabs-swiper
npm run parse u-tag
npm run parse u-td
npm run parse u-th
npm run parse u-time-line
npm run parse u-time-line-item
npm run parse u-toast
npm run parse u-top-tips
npm run parse u-tr
npm run parse u-upload
npm run parse u-verification-code
npm run parse u-waterfall
echo '所有组件解析完成！'